import "server-only";

import { getAiRuntimeConfig, getProviderApiKey, type AiProvider } from "@/lib/ai";
import { createMockAiProvider, createOpenAiProvider } from "@/lib/ai/providers";
import type { AdminContext } from "@/lib/auth/admin";
import type { EmbeddingRow } from "@/types/database";

import { loadEmbeddableDocuments, type EmbeddableDocument, type EmbeddableEntityType } from "../embeddings";

export type RetrievalEvidenceItem = {
  confidence: "fact" | "inference";
  metrics: Record<string, number>;
  record_id: string;
  record_type: EmbeddableEntityType;
  score: number;
  snippet: string;
  timestamp: null | string;
  user_id: string;
};

export type RetrievalResult = {
  items: RetrievalEvidenceItem[];
  mode: "embedding" | "keyword";
  reason?: string;
};

export type RetrievalQuery = {
  entityTypes?: EmbeddableEntityType[];
  limit?: number;
  query: string;
};

export type RetrievalOptions = {
  provider?: AiProvider | null;
};

const defaultLimit = 8;

function queryTokens(query: string) {
  return query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .map((token) => token.replace(/s$/, ""))
    .filter((token) => token.length >= 3);
}

function snippetFor(content: string, tokens: string[]) {
  const normalized = content.replace(/\s+/g, " ").trim();
  const lower = normalized.toLowerCase();
  const firstIndex = tokens.reduce((best, token) => {
    const index = lower.indexOf(token);
    if (index === -1) return best;
    return best === -1 ? index : Math.min(best, index);
  }, -1);
  const start = firstIndex === -1 ? 0 : Math.max(0, firstIndex - 60);

  return normalized.slice(start, start + 240);
}

function keywordScore(content: string, tokens: string[]) {
  const lower = content.toLowerCase();

  return tokens.reduce((score, token) => {
    if (lower.includes(token)) return score + 1;
    return score;
  }, 0);
}

function itemFromDocument(document: EmbeddableDocument, score: number, query: string): RetrievalEvidenceItem {
  const tokens = queryTokens(query);

  return {
    confidence: "fact",
    metrics: document.metrics,
    record_id: document.entityId,
    record_type: document.entityType,
    score,
    snippet: snippetFor(document.content, tokens),
    timestamp: document.timestamp,
    user_id: document.userId,
  };
}

// SCA-496 (W-17): cosineSimilarity is no longer used — Postgres computes
// the score via halfvec_cosine_ops and returns it in the RPC result.

function defaultEmbeddingProvider(options: RetrievalOptions): AiProvider | null {
  if (options.provider !== undefined) return options.provider;

  const config = getAiRuntimeConfig();

  if (config.provider === "mock") {
    return createMockAiProvider();
  }

  const apiKey = getProviderApiKey("openai");
  if (!apiKey) return null;

  return createOpenAiProvider({
    apiKey,
    maxTokens: config.maxTokens,
    model: config.model,
  });
}

// SCA-496 (W-17): matchesEntityType / embeddingModelForRows /
// isCompatibleEmbeddingRow were used by the prior in-Node retrieval loop.
// The RPC now does entity-type filtering server-side and returns each
// row's embedding_model so the caller filters by configured model
// directly. These helpers are removed; CLAUDE.md §28.10 still documents
// the configured-model gate.

function metadataRecord(metadata: EmbeddingRow["metadata"]): Record<string, unknown> {
  if (!metadata || Array.isArray(metadata) || typeof metadata !== "object") return {};
  return metadata as Record<string, unknown>;
}

function metricsFromMetadata(metadata: EmbeddingRow["metadata"]) {
  const metrics = metadataRecord(metadata).metrics;

  if (!metrics || Array.isArray(metrics) || typeof metrics !== "object") return {};

  return Object.entries(metrics).reduce<Record<string, number>>((result, [key, value]) => {
    if (typeof value === "number" && Number.isFinite(value)) {
      result[key] = value;
    }

    return result;
  }, {});
}

function timestampFromMetadata(metadata: EmbeddingRow["metadata"]) {
  const timestamp = metadataRecord(metadata).source_timestamp;
  return typeof timestamp === "string" ? timestamp : null;
}

// SCA-496 (W-17): convert a float32 query embedding into the halfvec text
// literal Postgres accepts. Format is the same `[a,b,c,...]` that
// pgvector reads for both vector and halfvec.
//
// Precision note: the embedding generated by the AI provider is float32,
// the wire format here is decimal text, and Postgres parses it into a
// halfvec (float16). This is a lossy round-trip by design — OpenAI's own
// docs recommend halfvec storage for text-embedding-3-large because the
// precision loss is far below the noise floor of cosine similarity for
// retrieval. Do not add a "precision regression" baseline against the
// float32 path; that's not the contract.
function formatEmbeddingAsHalfvec(values: number[]): string {
  return `[${values.join(",")}]`;
}

async function embeddingRetrieval(admin: AdminContext, input: RetrievalQuery, provider: AiProvider): Promise<RetrievalResult | null> {
  // SCA-496 (W-17): server-side top-k similarity. Replaces the prior
  // `select(*).limit(500)` + JS cosine loop that pulled ~12 MB and ran
  // ~1.5M FP ops per query. The RPC consults the halfvec HNSW index
  // added in phase 26 (M-16) and ships only top-k rows back to Node
  // — the embedding vectors themselves never cross the wire.
  const model = (getAiRuntimeConfig().embeddingModel ?? "").toString();
  const response = await provider.embed({ input: input.query, model });
  const queryEmbedding = response.embeddings[0];
  if (!queryEmbedding) return null;

  const limit = input.limit ?? defaultLimit;
  const { data, error } = await admin.supabase.rpc("creatoros_retrieve_embeddings_by_similarity", {
    p_entity_types: input.entityTypes ?? null,
    // Over-fetch by 2× so model-mismatched rows can be filtered without starving the result.
    p_limit: Math.max(limit * 2, limit),
    p_query_embedding: formatEmbeddingAsHalfvec(queryEmbedding) as never,
    p_user_id: admin.userId,
  });

  if (error) {
    throw new Error(`Failed to load embeddings for retrieval: ${error.message}`);
  }

  const rows = (data ?? []) as Array<{
    content: string;
    created_at: string;
    embedding_model: string;
    entity_id: string;
    entity_type: string;
    id: string;
    metadata: EmbeddingRow["metadata"];
    score: number;
    updated_at: null | string;
    user_id: string;
  }>;

  // Drop rows whose embedding model doesn't match the current model
  // — their score is meaningless under a different embedding space.
  const compatibleRows = rows.filter((row) => row.embedding_model === model);
  if (compatibleRows.length === 0) return null;

  const items = compatibleRows
    .map((row) => ({
      confidence: "fact" as const,
      metrics: metricsFromMetadata(row.metadata),
      record_id: row.entity_id,
      record_type: row.entity_type as EmbeddableEntityType,
      score: row.score,
      snippet: snippetFor(row.content, queryTokens(input.query)),
      timestamp: timestampFromMetadata(row.metadata) ?? row.updated_at ?? row.created_at,
      user_id: row.user_id,
    }))
    .filter((item) => item.score > 0)
    .slice(0, limit);

  if (items.length === 0) return null;
  return { items, mode: "embedding" };
}

async function keywordRetrieval(admin: AdminContext, input: RetrievalQuery, reason?: string): Promise<RetrievalResult> {
  const tokens = queryTokens(input.query);
  const documents = await loadEmbeddableDocuments(admin, { entityTypes: input.entityTypes, limit: 500 });
  const items = documents
    .map((document) => ({ document, score: keywordScore(document.content, tokens) }))
    .filter((entry) => entry.score > 0)
    .sort((left, right) => right.score - left.score || (right.document.timestamp ?? "").localeCompare(left.document.timestamp ?? ""))
    .slice(0, input.limit ?? defaultLimit)
    .map((entry) => itemFromDocument(entry.document, entry.score, input.query));

  return {
    items,
    mode: "keyword",
    reason,
  };
}

export async function retrieveEvidence(admin: AdminContext, input: RetrievalQuery, options: RetrievalOptions = {}): Promise<RetrievalResult> {
  const query = input.query.trim();

  if (!query) {
    return { items: [], mode: "keyword", reason: "empty_query" };
  }

  const provider = defaultEmbeddingProvider(options);

  if (provider) {
    try {
      const embedded = await embeddingRetrieval(admin, { ...input, query }, provider);
      if (embedded) return embedded;
    } catch (error) {
      console.error("Embedding retrieval failed; using keyword fallback", {
        reason: error instanceof Error ? error.message : "unknown",
      });
      return keywordRetrieval(admin, { ...input, query }, "embedding_query_failed");
    }
  }

  return keywordRetrieval(admin, { ...input, query }, provider ? "no_embedding_matches" : "embedding_provider_unavailable");
}
